# Generated by Django 5.1.3 on 2024-11-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_category_author"),
        ("excuse", "0002_remove_excuse_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="excuses",
            field=models.ManyToManyField(related_name="categories", to="excuse.excuse"),
        ),
    ]
