# Generated by Django 5.1.3 on 2024-11-14 00:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_category_excuses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category",
        ),
    ]
