# Generated by Django 5.1.3 on 2024-11-17 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0004_rename_name_category_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="author",
        ),
        migrations.RemoveField(
            model_name="category",
            name="excuses",
        ),
    ]
