# Generated by Django 5.1.3 on 2024-11-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("excuse", "0003_excuse_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="excuse",
            name="author",
        ),
        migrations.AddField(
            model_name="excuse",
            name="category",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("school", "School"),
                    ("family", "Family"),
                    ("friends", "Friends"),
                    ("relationship", "Relationship"),
                    ("coding", "Coding"),
                    ("other", "Other"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="excuse",
            name="nickname",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
